/*
 * Encryption utilites
 * Bradley Williams
 * {allegra,ihnp4,uiucdcs,ctvax}!convex!williams
 */

#include <stdio.h>
#include <curses.h>

#if defined(BSD42) || defined(BSD43)
#include <sys/file.h>
#else
#include <sys/fcntl.h>
#endif

#include "sc.h"

extern char curfile[];
char *strcpy();
int Crypt = 0;

#define DEFWIDTH 10
#define DEFPREC 2

creadfile (fname, eraseflg)
char *fname;
{
	register FILE *f;
	int pipefd[2];
	int fildes;
	int pid;
	char save[1024];

	if (*fname == 0) fname = &curfile[0];
	strcpy(save,fname);

	if (eraseflg && strcmp(fname,curfile) && modcheck(" first")) return;

	fildes = open (save, O_RDONLY, 0);
	if (fildes < 0)
	{
		error ("Can't read %s", save);
		return;
	}

	if (eraseflg) erasedb ();

	pipe (pipefd); /* make pipe to child */
	deraw();
	if ((pid=fork()) == 0) /* if child */
	{
		close (0); /* close stdin */
		close (1); /* close stdout */
		close (pipefd[0]); /* close pipe input */
		dup (fildes); /* standard in from file */
		dup (pipefd[1]); /* connect to pipe */
		fprintf (stderr, " ");
		execl ("/bin/sh", "sh", "-c", "crypt", 0);
		exit (-127);
	}
	else /* else parent */
	{
		close (fildes);
		close (pipefd[1]); /* close pipe output */
		f = fdopen (pipefd[0], "r");
		if (f == 0)
		{
			kill (pid, -9);
			error ("Can't fdopen file %s", save);
			close (pipefd[0]);
			return;
		}
	}

	while (fgets(line,sizeof line,f)) {
		linelim = 0;
		if (line[0] != '#') yyparse ();
	}
	fclose (f);
	close (pipefd[0]);
	while (pid != wait(&fildes)) /**/;
		goraw();
	linelim = -1;
	modflg++;
	if (eraseflg) {
		strcpy (curfile,save);
		modflg = 0;
	}
	EvalAll();
}

cwritefile (fname)
char *fname;
{
	register FILE *f;
	register struct ent **p;
	register r, c;
	int pipefd[2];
	int fildes;
	int pid;
	char save[1024];

	if (*fname == 0) fname = &curfile[0];

	strcpy(save,fname);
	
	fildes = open (save, O_WRONLY|O_CREAT, 0600);
	if (fildes < 0)
	{
		error ("Can't create %s", save);
		return(-1);
	}

	pipe (pipefd); /* make pipe to child */
	deraw();
	if ((pid=fork()) == 0) /* if child */
	{
		close (0); /* close stdin */
		close (1); /* close stdout */
		close (pipefd[1]); /* close pipe output */
		dup (pipefd[0]); /* connect to pipe input */
		dup (fildes); /* standard out to file */
		fprintf (stderr, " ");
		execl ("/bin/sh", "sh", "-c", "crypt", 0);
		exit (-127);
	}
	else /* else parent */
	{
		close (fildes);
		close (pipefd[0]); /* close pipe input */
		f = fdopen (pipefd[1], "w");
		if (f == 0)
		{
			kill (pid, -9);
			error ("Can't fdopen file %s", save);
			close (pipefd[1]);
			return(-1);
		}
	}

	fprintf (f, "# This data file was generated by the Spreadsheet ");
	fprintf (f, "Calculator.\n");
	fprintf (f, "# You almost certainly shouldn't edit it.\n\n");
	for (c=0; c<MAXCOLS; c++)
		if (fwidth[c] != DEFWIDTH || precision[c] != DEFPREC)
			fprintf (f, "format %s %d %d\n",coltoa(c),fwidth[c],precision[c]);
	for (r=0; r<=maxrow; r++) {
		p = &tbl[r][0];
		for (c=0; c<=maxcol; c++, p++)
			if (*p) {
				if ((*p)->label)
					fprintf (f, "%sstring %s%d = \"%s\"\n",
					         (*p)->flags&is_leftflush ? "left" : "right",
						         coltoa(c),r,(*p)->label);
				if ((*p)->flags&is_valid) {
					editv (r, c);
					fprintf (f, "%s\n",line);
				}
			}
	}
	fclose (f);
	close (pipefd[1]);
	while (pid != wait(&fildes)) /**/;
		strcpy(curfile,save);

	modflg = 0;
	error("File '%s' written.",curfile);
	goraw();
	return(0);
}